### ISSUE TITLE
Pass a reference to the app through to the scope

### ISSUE THREAD

**Issue by zero20nemvp** [rack-app/rack-app-front_end#4]
Problem

I would like use the logging from the app in the helper methods

Proposed Solution:

I would like to suggest that you add a initialiser to the scope and pass through the app.

<img width="521" alt="Screenshot 2023-08-02 at 10 38 40" src="https://github.com/rack-app/rack-app-front_end/assets/141216207/cb6d15f3-7c3b-4022-9ec5-705238fb6a98">

<img width="845" alt="Screenshot 2023-08-02 at 10 36 45" src="https://github.com/rack-app/rack-app-front_end/assets/141216207/94df9670-0607-4c05-b40c-ab926412e179">

this allows me to do this

<img width="521" alt="Screenshot 2023-08-02 at 10 37 51" src="https://github.com/rack-app/rack-app-front_end/assets/141216207/026062de-5f86-4bc6-8fa8-c8f217f6b4f2">

if there is a better way to do this or I have missed something  any feedback would be appreciated.

**Comment by adamluzsi** [comment]
Hello @vidtreonou ,

Thank you for getting in touch, and I sincerely apologize for the delay in my response.
It seems I'm not the best at keeping up with GitHub notifications!

About your question, you should have full access to all instance variables from your app instance within templates and helper methods. 
So, if your logger is defined as an instance variable in your application, you should be able to access it using the @ prefix.

However, I'd like to point out that, typically, the view layer's primary responsibility is to present content. I'm curious about the specific scenario that necessitates logging directly from the template. If you're open to discussing this, perhaps we can brainstorm a way to handle this differently, potentially avoiding direct logging from the template altogether.

In any case, I'm here to assist, and I'll provide a basic example of accessing the logger from your template:


```ruby
require 'rack/app'
require 'rack/app/front_end'

class App < Rack::App

  apply_extensions :front_end

  def initialize
    @logger = MyLogger.new
  end

  helpers do
         
    def my_helper_func
      @logger.debug "foo"
    end

  end

  get '/some_url' do
    render 'my_template.html.erb'
  end

end
```

> my_template.html.erb
```erb
<% @logger.debug "bar" %>
<% my_helper_func %>
```

(The example might have errors since I wrote it from memory.)

I look forward to hearing more about your project and how I can further help!

Warm regards,
Adam

**Comment by adamluzsi** [comment]
I overlooked mentioning this earlier, @vidtreonou, but your suggestion is spot-on!

I'd just like to understand how often users need logging access from the view layer during template rendering. 
This might be addressing a symptom rather than the root issue. Making complex objects easily accessible might inadvertently promote their use instead of addressing the core problem.

For instance, there shouldn't be a need for extensive logging in the helper functions. 
By the time of rendering, data should be prepped and ready. 
The view/template layer should simply represent this data without much cyclomatic complexity.

**Comment by zero20nemvp** [comment]
@adamluzsi  thanks for getting back to me, it is appreciated

`
require 'rack/app'
require 'rack/app/front_end'

class App < Rack::App

  apply_extensions :front_end
  apply_extensions :logger
  
  helpers do
         
    def my_helper_func
      @logger.debug "foo"
    end

  end

  get '/' do
    render 'index.html.erb'
  end

end

run App
`

when I run this code, I get
![Screenshot 2023-08-18 at 09 27 55](https://github.com/rack-app/rack-app-front_end/assets/141216207/a9a89031-c9b5-4466-8e22-6481cba49f98)

with this logger it creates an id which allows me to trace right the way through the code including the views. this can be helpful. Admittedly I guess this Is a good argument for keeping the helpers as small as possible but the ability trace calls all the way through can not harm.

**Comment by zero20nemvp** [comment]
I am definitely up for a brainstorming session to fugues this out , would be a great opportunity to learn and contribute. I would also like to discuss the issue of two places for params, params and request.params. so shout when you are free.

**Comment by adamluzsi** [comment]
To address your issue, ensure the @logger instance variable is set before its utilization. While there are several ways to achieve this, it appears you're employing the logger extension, not a custom logger. This extension employs a lazy loading method, so a simple logger method invocation should initialize the @logger instance variable for you.

Your feedback has illuminated a potential usability concern. I'm considering refining the core rack-app library to preload the logger instance variable through a before hook, thereby streamlining the process for users like yourself.

In the meantime, here's an example that illustrates how to achieve consistent initialization for the logger instance variable using a before hook:

```ruby
require 'logger'
require 'rack/app'
require 'rack/app/front_end'

class App < Rack::App

  apply_extensions :front_end
  apply_extensions :logger

  # Here we trigger an eager loading for the @logger instance variable 
  # by calling the logger method in a before block
  # that runs before every endpoint block.
  before { logger }
  
  helpers do

    def my_helper
      @logger.debug "foo"
    end

  end

  get "/" do
    render "index.html.erb"
  end
  
end

run App 
```

**Comment by adamluzsi** [comment]
I've just released rack-app 8.1.0 on rubygems.org. 
Upgrading to this version will eliminate the need for the previous workaround using the before hook in your project.

Cheers, Adam \o/

**Comment by adamluzsi** [comment]
https://rubygems.org/gems/rack-app

**Comment by zero20nemvp** [comment]
Wow! that is so cool , much appreciated and thank you! .

**Comment by adamluzsi** [comment]
The key question: did it address your use case?
 f you're still facing challenges, our work isn't finished. 🚀

**Comment by zero20nemvp** [comment]
hey , sorry for the delay getting back.

Works perfectly!  

`before { logger }. `

As a bonus ,  I learned more about the need for before and after hooks. so you help has been hugely appreciated.

**Comment by adamluzsi** [comment]
I'm glad I was able to help 🙌
