### ISSUE TITLE
request.params is not the same as params

### ISSUE THREAD

**Issue by zero20nemvp** [rack-app/rack-app-front_end#6]
Given

![Screenshot 2023-09-08 at 21 55 42](https://github.com/rack-app/rack-app-front_end/assets/141216207/b77d0b97-1700-4c73-b5eb-16f771a0639d)

when I call the script

![Screenshot 2023-09-08 at 21 56 12](https://github.com/rack-app/rack-app-front_end/assets/141216207/47e49979-df8d-4d91-b619-076dd8182d47)

I get the following logging out put

![Screenshot 2023-09-08 at 21 57 23 1](https://github.com/rack-app/rack-app-front_end/assets/141216207/046a1bfc-c1ee-405d-9758-6d3c5f9b94bc)

@adamluzsi there is a difference between the params collections. I have observed that the request.params does not include path params or  but it does contain params for forms.

can you please confirm If this is by design.

**Comment by adamluzsi** [comment]
[:rack-request:]: https://github.com/rack/rack/blob/main/lib/rack/request.rb

The `request` object here is a [Rack::Request][:rack-request:] instance. 

The [Rack::Request][:rack-request:] object in Ruby's Rack library offers a foundational interface for incoming HTTP requests, primarily wrapping the raw HTTP data in a user-friendly, object-oriented way.

Path parameters in frameworks like rack-app, Sinatra, or Rails represent a more advanced layer, deriving from RESTful API design principles that transform URL path segments into parameters.

While [Rack::Request][:rack-request:] processes raw HTTP data without inferring URL structure or routing, frameworks layered atop Rack introduce path parameters. 

In Rack::App, you have access to the following parameter methods in your endpoint:

- path_segments_params
  - only the params present in your path segments
- query_string_params
  - only the params present in your query string
- validated_params
  - Only the parameters passed your validation. Nothing else, to avoid hash key-value-based injections
- params
  - will return validated_params if validation is specified
  - Otherwise, it will merge all types of parameters into a hash map and return it.
  
I recognize that many frameworks adjust the request object, with some crafting their own. However, my goal with rack-app was to stay true to the core Rack experience. 

We currently use the original rack/request object without any modifications. I understand your perspective that a rack/app/request object might reduce confusion in a RESTful API design, especially when the path parameter isn't accessed via the params method.

**Comment by zero20nemvp** [comment]
They say Eveyday is a school day lol!  This a fantastic explanation.

I was getting confused because I use a mixture ways to send information through to endpoint and I was having to look in multiple places I appreciate the clarification.

My next part of the Rack-app journey was to understand an implement an extension.  I think this this looks like a good candidate to start and learn with.

rack/app/request 

I will take a crack at it and post the results here. 

Thanks for the speedy reply.

**Comment by adamluzsi** [comment]
@vidtreonou, my inclination towards minimalism usually keeps things straightforward, but in this instance, it seems to have missed the mark. Just as a joke shouldn't need explaining, neither should an API. I'm genuinely thinking about introducing a Rack::App::Request object to enhance the user experience.

**Comment by adamluzsi** [comment]
@vidtreonou, could I kindly ask that moving forward, you direct questions about rack-app to the [rack-app repository](https://github.com/rack-app/rack-app)? This space is primarily for front-end topics like template `render`ing. Sharing your insights there could be invaluable for others navigating past discussions.

We'll keep our current conversation here, and I'll make a note of it when diving into the `Rack::App::Request`. It's just a thought that discussions centered on rack-app's core functionality might fit better in that repository. I appreciate your flexibility on this!

**Comment by adamluzsi** [comment]
Would you mind reviewing this kickoff issue in the core project and sharing your thoughts? I'd appreciate any feedback, whether you find the solution acceptable or have a different perspective on the topic.

@vidtreonou, feel free to share your feedback here or directly on the kickoff issue. Either way works for me!

**Comment by adamluzsi** [comment]
https://github.com/rack-app/rack-app/issues/51

**Comment by zero20nemvp** [comment]
Would be a pleasure. 

Will let you know 

Delaney Burke
Founder

***@***.***
+372 533 22 524
vidtreon.com <http://vidtreon.com>




On September 9, 2023, GitHub ***@***.***> wrote:
> rack-app/rack-app#51 <https://github.com/rack-app/rack-app/issues/51>
>

—
Reply to this email directly, view it on GitHub
<https://github.com/rack-app/rack-app-front_end/issues/6#issuecomment-
1712591328>, or unsubscribe
<https://github.com/notifications/unsubscribe-
auth/BBVMTT2WF6SAVYZJ2K32MM3XZTECXANCNFSM6AAAAAA4QZD2VY>.
You are receiving this because you were mentioned.Message ID: <rack-
***@***.***>
